namespace MyProject;

/// <summary>
/// Placeholder type generated by the msl-csharp template. Replace it with your first real type —
/// and invest disproportionate care in it, because the first slice sets the pattern the next ten copy.
/// </summary>
public sealed class Class1
{
    /// <summary>Initializes a new instance of the <see cref="Class1"/> class.</summary>
    /// <param name="name">The name to greet.</param>
    public Class1(string name) => Name = name;

    /// <summary>Gets the name this instance greets.</summary>
    public string Name { get; }

    /// <summary>Builds a greeting for <see cref="Name"/>.</summary>
    /// <returns>The greeting.</returns>
    public string Greet() => $"Hello from {Name}.";
}
